# permissions for end users to edit csiisilons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiisilon-editor-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csiisilons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csiisilons/status
  verbs:
  - get
