# permissions for end users to view csiisilons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiisilon-viewer-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csiisilons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csiisilons/status
  verbs:
  - get
