# permissions for end users to view csipowerstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csipowerstore-viewer-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csipowerstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csipowerstores/status
  verbs:
  - get
