# permissions for end users to edit csipowerstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csipowerstore-editor-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csipowerstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csipowerstores/status
  verbs:
  - get
