# permissions for end users to edit csipowermaxrevproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csipowermaxrevproxy-editor-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csipowermaxrevproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csipowermaxrevproxies/status
  verbs:
  - get
