# permissions for end users to edit csiunities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiunity-editor-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csiunities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csiunities/status
  verbs:
  - get
