# permissions for end users to edit csivxflexos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csivxflexos-editor-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csivxflexos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csivxflexos/status
  verbs:
  - get
