# permissions for end users to view csivxflexos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csivxflexos-viewer-role
rules:
- apiGroups:
  - storage.dell.com
  resources:
  - csivxflexos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.dell.com
  resources:
  - csivxflexos/status
  verbs:
  - get
