apiVersion: storage.dell.com/v1
kind: CSIPowerMax
metadata:
  name: test-powermax
  namespace: test-powermax
spec:
  driver:
    # Config version for CSI PowerMax v1.7 driver
    configVersion: v6
    # Controller count. Don't increase it
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    common:
      # Image for CSI PowerMax driver v1.7
      image: dellemc/csi-powermax:v1.7.0
      imagePullPolicy: IfNotPresent
      envs:
        # list of arrays
        - name: X_CSI_MANAGED_ARRAYS
          value: "000000000000,000000000001"
        # Unisphere IP
        # If using PowerMax reverseproxy, leave it unchanged
        - name: X_CSI_POWERMAX_ENDPOINT
          value: "https://0.0.0.0:8443/"
        # Change this to a 3 character prefix unique for this cluster
        - name: X_CSI_K8S_CLUSTER_PREFIX
          value: "XYZ"
        # Add a list of comma separated port groups (only for ISCSI)
        - name: "X_CSI_POWERMAX_PORTGROUPS"
          value: ""
        # Preferred transport protocol (FC/ISCSI)
        - name: "X_CSI_TRANSPORT_PROTOCOL"
          value: ""
        # Set this to "powermax-reverseproxy" if you are installing the proxy
        - name: "X_CSI_POWERMAX_PROXY_SERVICE_NAME"
          value: ""
        # Set this value to a higher number (max 50) if you are using the proxy
        - name: "X_CSI_GRPC_MAX_THREADS"
          value: "4"
    node:
      envs:
        # Enable ISCSI CHAP Authentication
        - name: "X_CSI_POWERMAX_ISCSI_ENABLE_CHAP"
          value: "false"