apiVersion: storage.dell.com/v1
kind: CSIUnity
metadata:
  name: test-unity
  namespace: test-unity
spec:
  driver:
    configVersion: v5
    replicas: 2
    common:
      image: "dellemc/csi-unity:v1.6.0"
      imagePullPolicy: IfNotPresent
      envs:
      - name: X_CSI_UNITY_DEBUG
        value: "true"
      - name: X_CSI_UNITY_ALLOW_MULTI_POD_ACCESS
        value: "false"
      - name: X_CSI_MAX_VOLUMES_PER_NODE
        value: "0"
    sideCars:
      - name: provisioner
        args: ["--volume-name-prefix=csiunity","--default-fstype=ext4"]
      - name: snapshotter
        args: ["--snapshot-name-prefix=csiunitysnap"]